name: Java CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: agebe/ria-build:latest
    steps:
    - uses: actions/checkout@v3
#    - name: Set up JDK 17
#      uses: actions/setup-java@v3
#      with:
#        java-version: '17'
#        distribution: 'temurin'
#    - name: setup gradle
#      uses: gradle/gradle-build-action@v2
#      with:
#        gradle-version: current
    - name: execute gradle
      run: gradle build launcher
# https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts
    - name: Archive launcher
      uses: actions/upload-artifact@v3
      with:
        name: ria
        path: ria-launcher/build/launcher/ria
